### ISSUE TITLE
Missing Kernel_optimization.py

### ISSUE THREAD

**Issue by DanielAndreasen** [jdavidrcamacho/Gedi#1]
I can't run the `Tests.py` without this file.
Also, it could be nice with a `requirements.txt`. See other Python projects for the syntax. Then all dependencies can be installed with: `pip install -r requirements.txt`.

**Comment by jdavidrcamacho** [comment]
Oh that file is not in Gedi yet, I'm still running tests on it on Tests_GP,
Here [https://github.com/jdavidrcamacho/Tests_GP/tree/master/02%20-%20Programs%20being%20tested](url) you have all the files.

I'm still doing changes on that file, as soon as I can I will push it to github

**Comment by jdavidrcamacho** [comment]
And it would be a good idea if I started doing some sort of userguide of the files, to make things easier to anyone that comes here and try to use it, I'll do it as soon as I can :)

**Comment by DanielAndreasen** [comment]
No worries :) I was just curious. I don't need the software.

**Comment by jdavidrcamacho** [comment]
Sorry for the long waiting time xD

Made the first release
[https://pypi.python.org/pypi/Gedi/0.1](url)

If you wish you can install it via pip and give it a try :)
